name: Detect IB Gateway Releases

on:
  schedule:
    - cron: "0 6 * * *"

  workflow_dispatch:

defaults:
  run:
    shell: "bash -Eeuo pipefail -x {0}"

jobs:
  detect-release:
    runs-on: ubuntu-latest
    outputs:
      update: ${{ steps.check-update.outputs.has_update }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Latest Version
        id: version
        run: |
          res=$(curl -s https://download2.interactivebrokers.com/installers/tws/latest-standalone/version.json | sed 's/twslatest_callback(//g;s/);//g')
          build_version=$(jq -r '.buildVersion' <<< "$res")
          #build_dateTime=$(jq -r '.buildDateTime' <<< "$res")
          echo "build_version=$build_version" >> $GITHUB_OUTPUT
          #echo "build_dateTime=$build_dateTime" >> $GITHUB_OUTPUT

      - name: Check if there is an update
        id: check-update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release list > /tmp/ibgateway-releases
          if grep -qF 'ibgateway@${{ steps.version.outputs.build_version }}' /tmp/ibgateway-releases
          then
            echo "has_update=false" >> $GITHUB_OUTPUT
          else
            echo "has_update=true" >> $GITHUB_OUTPUT
          fi

      - name: Download
        if: ${{ steps.check-update.outputs.has_update == 'true' }}
        run: |
          download_url='https://download2.interactivebrokers.com/installers/ibgateway/latest-standalone/ibgateway-latest-standalone-linux-x64.sh'
          dest='ibgateway-${{ steps.version.outputs.build_version }}-standalone-linux-x64.sh'
          curl -sSL "$download_url" --output "$dest"
          sha256sum "$dest" > "${dest}.sha256"

      - name: Create release
        if: ${{ steps.check-update.outputs.has_update == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create 'ibgateway@${{ steps.version.outputs.build_version }}' \
            -t 'IB Gateway ${{ steps.version.outputs.build_version }}' \
            -n 'IB Gateway ${{ steps.version.outputs.build_version }} release files' \
            ibgateway-*

      - name: Update Dockerfile version
        if: ${{ steps.check-update.outputs.has_update == 'true' }}
        run: |
          # Update version in Dockerfile
          sed -i "s/ENV IB_GATEWAY_VERSION=.*/ENV IB_GATEWAY_VERSION=${{ steps.version.outputs.build_version }}/" Dockerfile

      - name: Update README
        if: ${{ steps.check-update.outputs.has_update == 'true' }}
        run: |
          # Get version from Dockerfile
          export LATEST_VERSION=${{ steps.version.outputs.build_version }}
          export LATEST_MINOR=$(echo $LATEST_VERSION | cut -d '.' -f1,2)
          export STABLE_VERSION=$LATEST_VERSION
          export STABLE_MINOR=$LATEST_MINOR
          # IBC version
          export IBC_VERSION="$(grep 'ENV IBC_VERSION' Dockerfile | cut -d '=' -f 2)"
          # show in log
          echo "VERSION=$LATEST_VERSION, MINOR=$LATEST_MINOR, IBC=$IBC_VERSION"
          # replace variables
          envsubst '$LATEST_VERSION,$LATEST_MINOR,$STABLE_VERSION,$STABLE_MINOR,$IBC_VERSION' < template_README.md > README.md

      - name: Create PR
        if: ${{ steps.check-update.outputs.has_update == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          t_branch='update-to-${{ steps.version.outputs.build_version }}'
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git checkout -b "$t_branch" origin/master
          git add Dockerfile README.md
          git commit -m 'Update IB Gateway to `${{ steps.version.outputs.build_version }}`'
          git push --set-upstream origin "$t_branch"

          gh pr create --base master --fill


  build:
    name: Call build workflow
    needs: detect-release
    if: needs.detect-release.outputs.update == 'true'
    uses: gnzsnz/ib-gateway-docker/.github/workflows/build.yml@master
